# Initialization

In [ ]:
try:
    # excecuting in Colab
    from google.colab import drive, runtime
    drive.mount('/content/gdrive', force_remount=True)
    using_colab = True
    root_dir = '/content/gdrive/MyDrive/oc_projet_9'


except:
    # excecuting locally
    using_colab = False
    root_dir = 'D:/OpenClassrooms/projet_9'

Mounted at /content/gdrive

In [ ]:
import os

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

if using_colab:
    import gdrive.MyDrive.oc_projet_9.scripts.project_9_functions as pf
else:
    import project_9_functions as pf

from IPython.display import clear_output

In [ ]:
if using_colab:
    # colab paths
    clicks_sample_path = 'clicks_sample.csv'
    articles_metadata_path = 'articles_metadata.csv'
    articles_embeddings_path = 'articles_embeddings.pickle'
    clicks_dir_path = 'clicks/'
    clicks_file = 'clicks_hour_'

    zip_path = root_dir + '/data/' + 'news-portal-user-interactions-by-globocom.zip'
    zip_clicks_path = 'clicks.zip'
    path_list = [clicks_sample_path, articles_metadata_path, articles_embeddings_path, clicks_dir_path]

    already_unziped = True
    for path in path_list:
        if not os.path.exists(path):
            print(path)
            already_unziped = False

    if already_unziped:
        print('data already unziped')
    else:
        !unzip $zip_path
        !unzip $zip_clicks_path
        clear_output()


else:
    # local paths
    clicks_sample_path = root_dir + '/data/' + 'clicks_sample.csv'
    articles_metadata_path = root_dir + '/data/' + 'articles_metadata.csv'
    articles_embeddings_path = root_dir + '/data/' + 'articles_embeddings.pickle'
    clicks_dir_path = root_dir + '/data/clicks/'
    clicks_file = 'clicks_hour_'

data already unziped

In [ ]:
test_mode = False

### articles metadata

In [ ]:
articles_metadata = pd.read_csv(articles_metadata_path)
articles_metadata

        article_id  category_id  created_at_ts  publisher_id  words_count
0                0            0  1513144419000             0          168
1                1            1  1405341936000             0          189
2                2            1  1408667706000             0          250
3                3            1  1408468313000             0          230
4                4            1  1407071171000             0          162
...            ...          ...            ...           ...          ...
364042      364042          460  1434034118000             0          144
364043      364043          460  1434148472000             0          463
364044      364044          460  1457974279000             0          177
364045      364045          460  1515964737000             0          126
364046      364046          460  1505811330000             0          479

[364047 rows x 5 columns]

In [ ]:
articles_metadata.describe()

,article_id,category_id,created_at_ts,publisher_id,words_count
count,364047.000000,364047.000000,3.640470e+05,364047.0,364047.000000
mean,182023.000000,283.108239,1.474070e+12,0.0,190.897727
std,105091.461061,136.723470,4.293038e+10,0.0,59.502766
min,0.000000,0.000000,1.159356e+12,0.0,0.000000
25%,91011.500000,199.000000,1.444925e+12,0.0,159.000000
50%,182023.000000,301.000000,1.489422e+12,0.0,186.000000
75%,273034.500000,399.000000,1.509891e+12,0.0,218.000000
max,364046.000000,460.000000,1.520943e+12,0.0,6690.000000

In [ ]:
# publisher_id has only one value, delete column
articles_metadata = articles_metadata.drop(['publisher_id'], axis=1)

### clicks

In [ ]:
clicks = pf.get_clicks_df(test_mode, clicks_sample_path, clicks_dir_path)
clicks

,user_id,session_id,session_start,session_size,click_article_id,click_timestamp,click_environment,click_deviceGroup,click_os,click_country,click_region,click_referrer_type
0,0,1506825423271737,1506825423000,2,157541,1506826828020,4,3,20,1,20,2
1,0,1506825423271737,1506825423000,2,68866,1506826858020,4,3,20,1,20,2
2,1,1506825426267738,1506825426000,2,235840,1506827017951,4,1,17,1,16,2
3,1,1506825426267738,1506825426000,2,96663,1506827047951,4,1,17,1,16,2
4,2,1506825435299739,1506825435000,2,119592,1506827090575,4,1,17,1,24,2
...,...,...,...,...,...,...,...,...,...,...,...,...
2564,10051,1508211372158328,1508211372000,2,84911,1508211557302,4,3,2,1,25,1
2565,322896,1508211376302329,1508211376000,2,30760,1508211672520,4,1,17,1,25,2
2566,322896,1508211376302329,1508211376000,2,157507,1508211702520,4,1,17,1,25,2
2567,123718,1508211379189330,1508211379000,2,234481,1508211513583,4,3,2,1,25,2
2568,123718,1508211379189330,1508211379000,2,233578,1508211543583,4,3,2,1,25,2

## "time_clicks" dataframe
#### (this dataframe is used by the api to get the list of read articles by a user)

In [ ]:
time_click = clicks[['user_id', 'click_article_id', 'click_timestamp']]
time_click

     user_id click_article_id click_timestamp
0          0           157541   1506826828020
1          0            68866   1506826858020
2          1           235840   1506827017951
3          1            96663   1506827047951
4          2           119592   1506827090575
...      ...              ...             ...
2564   10051            84911   1508211557302
2565  322896            30760   1508211672520
2566  322896           157507   1508211702520
2567  123718           234481   1508211513583
2568  123718           233578   1508211543583

[2988181 rows x 3 columns]

In [ ]:
# sort by date
time_click.sort_values('click_timestamp', ascending=False)

     user_id click_article_id click_timestamp
1700  320431           145309   1510603454886
1699  320431           203538   1510603424886
3284  252642            96333   1510093912860
3283  252642           207672   1510093882860
7270  201738           224148   1509798422502
...      ...              ...             ...
187       70           119592   1506826818863
295      111           202436   1506826814140
399      154            96663   1506826804207
208       79           159359   1506826801702
147       59           234853   1506826800026

[2988181 rows x 3 columns]

In [ ]:
nb_users = len(time_click['user_id'].unique())
nb_users

322897

In [ ]:
user_id = 0
group_user = time_click[time_click['user_id'] == user_id]
group_user

     user_id click_article_id click_timestamp
0          0           157541   1506826828020
1          0            68866   1506826858020
7412       0            96755   1507340033155
7413       0           313996   1507340063155
4881       0           160158   1507388090915
4882       0           233470   1507388120915
1811       0            87224   1507514056617
1812       0            87205   1507514086617

In [ ]:
sorted_group = group_user.sort_values('click_timestamp', ascending=False)
sorted_group

     user_id click_article_id click_timestamp
1812       0            87205   1507514086617
1811       0            87224   1507514056617
4882       0           233470   1507388120915
4881       0           160158   1507388090915
7413       0           313996   1507340063155
7412       0            96755   1507340033155
1          0            68866   1506826858020
0          0           157541   1506826828020

In [ ]:
list(sorted_group['click_article_id'])

[87205, 87224, 233470, 160158, 313996, 96755, 68866, 157541]

In [ ]:
user_id = 0

group_user = time_click[time_click['user_id'] == user_id]
sorted_group = group_user.sort_values('click_timestamp', ascending=False)
read_list = list(sorted_group['click_article_id'])

print(read_list)

[87205, 87224, 233470, 160158, 313996, 96755, 68866, 157541]

In [ ]:
# save & load back
filename = 'time_click_test' if test_mode else 'time_click'

time_click_path = root_dir + '/data/' + filename + '.pkl'
time_click.to_pickle(time_click_path)
time_click = pd.read_pickle(time_click_path)

print(time_click_path)
print(time_click.shape)

/content/gdrive/MyDrive/oc_projet_9/data/time_click.pkl
(2988181, 3)

In [ ]:
# function included in api
%%time

user_id = 0

read = pf.get_user_read_list(user_id, time_click)
read

CPU times: user 163 ms, sys: 656 Âµs, total: 163 ms
Wall time: 165 ms

[87205, 87224, 233470, 160158, 313996, 96755, 68866, 157541]

In [ ]:
kill_session = False

if kill_session and using_colab:
    # kill colab session
    runtime.unassign()